SELECT `user`.`id`,
    `user`.`username`,
    `user`.`password`,
    `user`.`major`,
    `user`.`year`,
    `user`.`usertype`,
    `user`.`register_time`,
    `user`.`email`,
    `user`.`goods_bought`,
    `user`.`goods_sold`,
    `user`.`rate_goods`,
    `user`.`rate_request`,
    `user`.`request_published_finished`,
    `user`.`request_taken_finished`
FROM `fudanmarket`.`user`;
SELECT `goods`.`id`,
    `goods`.`name`,
    `goods`.`remark`,
    `goods`.`price`,
    `goods`.`uid`,
    `goods`.`goods_type`,
    `goods`.`sort_by_goods`,
    `goods`.`sort_by_major`,
    `goods`.`pic`,
    `goods`.`release_time`,
    `goods`.`state`,
    `goods`.`degree`,
    `goods`.`address`,
    `goods`.`bid`,
    `goods`.`buy_time`,
    `goods`.`contact`,
    `goods`.`semester`,
    `goods`.`rate`
FROM `fudanmarket`.`goods`;
SELECT `goods_weight`.`id`,
    `goods_weight`.`buyer_major`,
    `goods_weight`.`sort_by_goods`,
    `goods_weight`.`weight`
FROM `fudanmarket`.`goods_weight`;
SELECT `request`.`id`,
    `request`.`description`,
    `request`.`finish_time`,
    `request`.`finish_user_id`,
    `request`.`name`,
    `request`.`remark`,
    `request`.`request_time`,
    `request`.`request_user_id`,
    `request`.`sort_by_goods`,
    `request`.`sort_by_major`,
    `request`.`state`,
    `request`.`major`,
    `request`.`middle`,
    `request`.`minor`,
    `request`.`address`,
    `request`.`contact`,
    `request`.`price`,
    `request`.`time`
FROM `fudanmarket`.`request`;
